In [1]:
x = [1, 2, 4, 6, 12, 15, 25, 25, 68, 67, 64, 98]

In [2]:
import numpy as np

In [3]:
np.mean(x)

32.25

In [4]:
np.std(x)

31.63364506344471

In [6]:
x = [12, 23, 34, 44, 59, 70, 98]

In [7]:
np.mean(x)

48.57142857142857

In [8]:
np.std(x)

27.348842455823785

In [9]:
np.var(x)

747.9591836734695

In [ ]:
# A single dimension
# Mean
# Standard Deviation
# Variance


In [ ]:
# Two variables (X and Y)
# Covariance


In [10]:
f1 = [9,15,25,14,10,18,0,16,5,19,16,20]

f2 = [39,56,93,61,50,75,32,85,42,70,66,80]

In [12]:

f1_mean = np.mean(f1)
f2_mean = np.mean(f2)

In [13]:
f1_mean

13.916666666666666

In [14]:
f2_mean

62.416666666666664

In [26]:
val = 0
for i in range(len(f1)):
    val += (f1[i] - f1_mean)*(f2[i] - f2_mean)
print(val)
avg = val/len(f1)
print(avg)

1352.4166666666667
112.7013888888889


In [ ]:
# Covarience between two features F1 and F2

112

In [ ]:

# Multiple features

f1 f2 f3 f4 .....


cov_matix  =  

(f1, f1)    (f1, f2)     (f1, f3)    (f1, f4)
(f2, f1)    (f2, f2)     (f2, f3)    (f2, f4)
(f3, f1)    (f3, f2)     (f3, f3)    (f3, f4)
(f4, f1)    (f4, f2)     (f4, f3)    (f4, f4)

    

In [37]:
f1 = [1, -1, 4]
f2 = [2, 1, 3]
f3 = [1, 3, -1]

In [38]:
f1

[1, -1, 4]

In [39]:
f2

[2, 1, 3]

In [40]:
f3

[1, 3, -1]

In [44]:
f1_mean = np.mean(f1)
f2_mean = np.mean(f2)
f3_mean = np.mean(f3)

In [46]:
val = 0
for i in range(len(f1)):
    val += (f1[i] - f1_mean)*(f1[i] - f1_mean)
# print(val)
f1_f1_cov = val/len(f1)
print(f1_f1_cov)

4.222222222222222


In [48]:
val = 0
for i in range(len(f1)):
    val += (f1[i] - f1_mean)*(f2[i] - f2_mean)
# print(val)
f1_f2_cov = val/len(f1)
print(f1_f2_cov)

1.6666666666666667


In [49]:
val = 0
for i in range(len(f1)):
    val += (f1[i] - f1_mean)*(f3[i] - f3_mean)
# print(val)
f1_f3_cov = val/len(f1)
print(f1_f3_cov)

-3.3333333333333335


In [50]:
val = 0
for i in range(len(f1)):
    val += (f2[i] - f2_mean)*(f1[i] - f1_mean)
# print(val)
f2_f1_cov = val/len(f1)
print(f2_f1_cov)

1.6666666666666667


In [51]:
val = 0
for i in range(len(f1)):
    val += (f2[i] - f2_mean)*(f2[i] - f2_mean)
# print(val)
f2_f2_cov = val/len(f1)
print(f2_f2_cov)

0.6666666666666666


In [52]:
val = 0
for i in range(len(f1)):
    val += (f2[i] - f2_mean)*(f3[i] - f3_mean)
# print(val)
f2_f3_cov = val/len(f1)
print(f2_f3_cov)

-1.3333333333333333


In [53]:
val = 0
for i in range(len(f1)):
    val += (f3[i] - f3_mean)*(f1[i] - f1_mean)
# print(val)
f3_f1_cov = val/len(f1)
print(f3_f1_cov)

-3.3333333333333335


In [54]:
val = 0
for i in range(len(f1)):
    val += (f3[i] - f3_mean)*(f2[i] - f2_mean)
# print(val)
f3_f2_cov = val/len(f2)
print(f3_f2_cov)

-1.3333333333333333


In [55]:
val = 0
for i in range(len(f1)):
    val += (f3[i] - f3_mean)*(f3[i] - f3_mean)
# print(val)
f3_f3_cov = val/len(f3)
print(f3_f3_cov)

2.6666666666666665


In [60]:
cov_mat = [[f1_f1_cov, f1_f2_cov, f1_f3_cov], [f2_f1_cov, f2_f2_cov, f2_f3_cov], [f3_f1_cov, f3_f2_cov, f3_f3_cov]]

In [62]:
# Features
cov_mat 


[[4.222222222222222, 1.6666666666666667, -3.3333333333333335],
 [1.6666666666666667, 0.6666666666666666, -1.3333333333333333],
 [-3.3333333333333335, -1.3333333333333333, 2.6666666666666665]]

In [ ]:
# Take a break : 11:15 join back

In [73]:
m = [[2, 3],[2, 1]]
m = np.matrix(m)
m

matrix([[2, 3],
        [2, 1]])

In [82]:
v = [[1], [3]]
v = np.matrix(v)
v

matrix([[1],
        [3]])

In [85]:
a = np.matmul(m, v)
a

matrix([[11],
        [ 5]])

In [86]:
m

matrix([[2, 3],
        [2, 1]])

In [87]:
v1 = [[3],[2]]

In [88]:
a1 = np.matmul(m, v1)

In [89]:
a1

matrix([[12],
        [ 8]])

In [91]:
# 4*a1 = v1

In [93]:
# 4*[[3],[2]]

In [94]:
# length of the vector = sqr((3^2 + 2^2)) = sqr(13)

<!-- PCA = (3/sqr(13), 2/sqrt(13)) -->

In [95]:
# PCA = 3/sqr(13), 2/sqrt(13)

In [96]:
# How to find eigen vector?

In [101]:
m = np.matrix([[3, 0, 1], [-4, 1, 2], [-6, 0, -2]])
m

matrix([[ 3,  0,  1],
        [-4,  1,  2],
        [-6,  0, -2]])

In [104]:
v1 = np.matrix([[2],[2], [-1]])
v1

matrix([[ 2],
        [ 2],
        [-1]])

In [103]:
m*v1

matrix([[  5],
        [ -8],
        [-10]])

In [105]:
v2 = np.matrix([[-1],[0], [2]])
v2

matrix([[-1],
        [ 0],
        [ 2]])

In [106]:
m*v2

matrix([[-1],
        [ 8],
        [ 2]])

In [109]:
v3 = np.matrix([[-1],[1], [3]])
v3

matrix([[-1],
        [ 1],
        [ 3]])

m*v3

In [110]:
m*v3

matrix([[ 0],
        [11],
        [ 0]])

In [111]:
v4 = np.matrix([[0],[1], [0]])
v4

matrix([[0],
        [1],
        [0]])

In [112]:
m*v4

matrix([[0],
        [1],
        [0]])

In [116]:
# eigen value = 1

In [113]:
v5 = np.matrix([[3],[2], [1]])
v5

matrix([[3],
        [2],
        [1]])

In [114]:
m*v5

matrix([[ 10],
        [ -8],
        [-20]])